apiVersion: v1
kind: Pod
metadata:
  name: command-demo-env-args
  labels:
    purpose: demostrate-command-args-env
spec:
  containers:
  - name: command-demo-container-env
    image: debian
    env:
    - name: MESSAGE
      value: "hello world"
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
  restartPolicy: OnFailure
